schemaVersion: 2.1.0
metadata:
  name: mongodb-devspace
components:
  - name: tools
    container:
      image: quay.io/devspaces/ubi8
      memoryLimit: 512Mi
      mountSources: true
  - name: mongodb
    container:
      image: mongo:latest
      memoryLimit: 512Mi
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
      endpoints:
        - name: mongo
          targetPort: 27017
  - name: mongo-express
    container:
      image: mongo-express:latest
      memoryLimit: 512Mi
      env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: password
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://admin:password@mongodb:27017/
      endpoints:
        - name: mongo-express
          targetPort: 8081
